#name, main, version and api are required
name: WorldGameMode
main: WorldGameMode\MainClass
version: 1.0.0
api: [1.0.0]

load: POSTWORLD
author: PocketMine Team
description: Example plugin showing the new API
commands:
 tpworld:
  description: Example command
  usage: "Usage: /tpworld <world>"
  permission: WorldGameMode.command.tpworld
permissions:
WorldGameMode.permission.tpworld:
  description: "Allows the user to run the tpworld command"
  default: true